---
services:
  db:
    image: docker.io/bitnamilegacy/cassandra:4.0.13
    restart: always
    environment:
      CASSANDRA_CLUSTER_NAME: "Test Cluster"
      CASSANDRA_DATACENTER: "test"
      CASSANDRA_USER: "cassandra"
      CASSANDRA_PASSWORD: "cassandra"
      CASSANDRA_RACK: "harlequin"
      CASSANDRA_CFG_YAML_enable_materialized_views: true
    volumes:
      - data:/var/lib/cassandra
    ports:
      - 9042:9042

volumes:
  data:
